# Generated by Django 4.1.2 on 2022-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('data_rozdenia', models.DateTimeField(verbose_name='Дата рождения')),
                ('gorod', models.CharField(max_length=255, verbose_name='Город')),
            ],
        ),
    ]
