# Generated by Django 4.1.2 on 2022-11-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
