# Generated by Django 4.1.3 on 2022-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sotrudnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('data_rozdenia', models.DateField(verbose_name='Дата рождения')),
                ('dolznost', models.CharField(max_length=255, verbose_name='Должность')),
                ('otdel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел')),
            ],
        ),
    ]
