# Generated by Django 4.1.3 on 2022-11-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_otdel_alter_sotrudnic_options_alter_sotrudnic_otdel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otdel',
            old_name='nazvane',
            new_name='nazvanie',
        ),
    ]
