# Generated by Django 4.1.3 on 2022-11-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_operazionasistema_tiptehniki_tehnika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otvetstveniy_sotrudnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Ответственный сотрудник',
                'verbose_name_plural': 'Ответственные сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='operazionasistema',
            options={'verbose_name': 'Название Операционной системы', 'verbose_name_plural': 'Название Операционных систем'},
        ),
        migrations.AlterModelOptions(
            name='sotrudnic',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='otdel',
            name='adres_otdela',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='otdel',
            name='korotkoye_nazvanie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое имя'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='adres_prozivania',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='passport_seria_nomer',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Паспорт Серия и номер'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='passport_vidan_kem_i_gde',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Паспорт выдан когда и где'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='photo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='pol',
            field=models.IntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], db_index=True, default=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='sotrudnic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='otdel',
            name='nazvanie',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sotrudnic',
            name='data_rozdenia',
            field=models.DateField(db_index=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='sotrudnic',
            name='dolznost',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='sotrudnic',
            name='fio',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='tehnika',
            name='operaziona_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.operazionasistema', verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='tehnika',
            name='otvestveni_sotrudnic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.otvetstveniy_sotrudnic', verbose_name='Ответсвенный человек'),
        ),
    ]
